defaults:
  - _self_
  - datamodule: av2_stream # av2_ma # CHANGE FOR USING MULTI-AGENT
  - model: Seam # Seam_ma # CHANGE FOR USING MULTI-AGENT

hydra:
  run:
    dir: ${output_dir}
  # output_subdir: ${output_dir}/hydra
  # job:
  #   chdir: True

seed: 2333
tag: ${model.tag}-${datamodule.tag}
output_dir: outputs/${tag}/${now:%Y%m%d-%H%M%S}

gpus: 2
batch_size: 8
epochs: 20
checkpoint:
submit:

callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${output_dir}/checkpoints
    filename: epoch_{epoch}-minADE6_{minADE6}
    monitor:  minADE6 # AvgMinFDE # CHANGE IF USING MULTI-AGENT
    mode: min
    save_top_k: -1
    save_last: True
    every_n_epochs: 1
    auto_insert_metric_name: False
  - _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: 1
  - _target_: pytorch_lightning.callbacks.RichProgressBar
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch

trainer:
  max_epochs: ${epochs}
  accelerator: gpu
  devices: ${gpus}
  strategy: ddp_find_unused_parameters_false
  gradient_clip_val: 5
  gradient_clip_algorithm: norm
  sync_batchnorm: true
  accumulate_grad_batches: 2
  default_root_dir: ${output_dir}
