tag: Seam

pl_module:
  _target_: src.model.pl_modules.StreamLightningModule
  num_grad_frame: 3
  ma: True
  model:
    _target_: src.model.seam.Seam
    embed_dim: 128
    future_steps: 60
    encoder_depth: 4
    num_heads: 8
    mlp_ratio: 4.0
    qkv_bias: False
    drop_path: 0.2
    use_stream_encoder: True
    use_stream_decoder: True
    use_target_context: True
    k: 6
    ma: True
  optim:
    lr: 1e-3
    weight_decay: 1e-2
    min_lr: 1e-5
    epochs: ${epochs}
    warmup_ratio: 0.0
